SCREEN_WIDTH = 800
SCREEN_HEIGHT = 608
#Rn this is for base camo
BASETILE_SIZE = 16

#PLAYER SPEED, MESSING AROUND
PLAYER_SPEED = 3
NPC_SPEED = .5
NUM_LIVES = 10
MELEE_RANGE = 80
WALL_LIFESPAN = 100
HEALTH_POTION_EFFECT = 3
PROJECTILE_SPEED = 10
#WIN CONDITIONS
L1_WIN = 10
L2_WIN = 10
L3_WIN = 10
L4_WIN = 10

#ENEMY CONSTANTS:
ENEMY_DAMAGE = 2
ENEMY_SPEED = 1.5


