SCREEN_WIDTH = 800
SCREEN_HEIGHT = 608
#Rn this is for base camo
BASETILE_SIZE = 16

#PLAYER SPEED, MESSING AROUND
PLAYER_SPEED = 3
NPC_SPEED = .5
NUM_LIVES = 10
MELEE_RANGE = 80
WALL_LIFESPAN = 100
HEALTH_POTION_EFFECT = 3
PROJECTILE_SPEED = 10
#WIN CONDITIONS
L1_WIN = 10
L2_WIN = 15
L3_WIN = 15
L4_WIN = 20

#ENEMY CONSTANTS, anything ENEMY referes to swordsmen
ENEMY_DAMAGE = 2
ENEMY_SPEED = 1.5
WIZARD_SPEED = 1
WIZARD_MELEE = 1
WIZARD_FIRE = 3
FIREBALL_CHANCE = 150
ENEMY_FIREBALL_SPEED = 5


